### PR TITLE
Upgrade Chosen to version 1.0.0

### LINKED ISSUE #30: Upgrade to Chosen 1.0.0
Chosen released version 1.0.0 a few months ago. There have been a number of improvements since 0.10.0, the current version in django-chosen.

Note that some changes will require a small amount of code refactoring (like using "chosen" instead of "chzn" for class names). See here for more details: https://github.com/harvesthq/chosen/releases/tag/1.0.0

### PR DESCRIPTION
**Pull request by sjdemartini**
Update static files to Chosen version 1.0.0 and change widgets.py accordingly.
Fixes #30

### CODE REVIEW

**Comment by sjdemartini** [comment]
Bump. Is it possible to get a review of this pull request and merge this in? Thanks.

**Comment by fdintino** [comment]
Sorry for the hold-up. We now use [django-select2-forms](https://github.com/theatlantic/django-select2-forms) instead of django-chosen, so this had fallen off my radar.

I made a comment [here](https://github.com/sjdemartini/django-chosen/commit/1c8f0471df7b6b915fa4858a4156aadd31afa00d#commitcomment-5202537). Everything else looks great; once that change has been made I'll merge it in as soon as I can.

**Comment by sjdemartini** [comment]
Thanks Frankie. Nice catch. I've fixed the chosen.jquery files accordingly. I appreciate the review. And I'll look into select2, as well. :)

**Comment by fdintino** [comment]
Thanks for your contribution. It looks good, I've pulled it into master.

**Pull request merged**
